# Generated by Django 5.1.7 on 2025-03-25 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='nom',
        ),
    ]
