# Generated by Django 5.1.7 on 2025-03-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('actif', models.BooleanField(default=True)),
                ('environnement', models.CharField(choices=[('IFS', 'IFS'), ('CFG', 'CFG')], default='IFS', max_length=3)),
            ],
        ),
    ]
